import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

// Define available languages
export type Language = 'en' | 'ru';

// Define context type
interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

// Create context with default values
const LanguageContext = createContext<LanguageContextType>({
  language: 'en',
  setLanguage: () => {},
  t: (key: string) => key,
});

// Define translations for both languages
const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navbar
    'navbar.logout': 'Logout',
    'navbar.credits': 'credits',
    'navbar.credit_info': 'Credit Information',
    'navbar.subscription_type': 'Subscription Type',
    'navbar.total_used': 'Total Used',
    'navbar.reset_date': 'Reset Date',
    'navbar.subscription_status': 'Subscription Status',
    'navbar.active': 'Active',
    'navbar.inactive': 'Inactive',
    'navbar.no_data': 'No data',
    
    // Hero section
    'hero.title': 'TelePublisher',
    'hero.description': 'Professional content management system for Telegram channels. Create, edit and publish content with ease.',
    'hero.start_free': 'Start for free',
    'hero.learn_more': 'Learn more',

    // Features section
    'features.title': 'Our features',
    'features.fast_publication': 'Fast publication',
    'features.fast_publication_description': 'Publish content instantly or schedule publications for future times.',
    'features.multiple_channels': 'Multiple channels',
    'features.multiple_channels_description': 'Manage multiple channels from a single admin panel.',
    'features.ai_content': 'AI Content Generation',
    'features.ai_content_description': 'Create high-quality content, images, and hashtags using advanced AI tools.',
    'features.content_management': 'Content management',
    'features.easy_interface': 'Easy interface',
    'features.easy_interface_description': 'Intuitive interface for comfortable content management.',
    'features.security': 'Security',
    'features.security_description': 'Login through Telegram without password transfer. We do not store sensitive data.',
    'features.privacy': 'Privacy',
    'features.privacy_description': 'We do not collect personal information and do not transfer data to third parties.',

    // Video section
    'video.title': 'See TelePublisher in Action',
    'video.description': 'Watch our tutorial to learn how to optimize your Telegram channel with our powerful tools',
    'video.channel_link': 'Visit our YouTube channel for more tutorials',

    // Pricing section
    'pricing.title': 'Pricing plans',
    'pricing.free': 'Free',
    'pricing.free_channels': 'Up to 2 channels',
    'pricing.basic-tools': 'Basic tools',
    'pricing.free_publications': '2-10 trial publications',
    'pricing.start-free': 'Start for free',
    'pricing.mounth': 'month',

    'pricing.popular': 'POPULAR',
    'pricing.standard': 'Standart',
    'pricing.standard_channels': 'Up to 10 channels',
    'pricing.standard_publications': 'Up to 100 publications',
    'pricing.standard_support': 'Priority support',
    'pricing.choose_plan': 'Choose plan',

    'pricing.business': 'Business',
    'pricing.business_channels': 'Unlimited number of channels',
    'pricing.business_publications': 'Up to 400 publications',
    'pricing.business_support': 'Dedicated support 24/7',

    // Security Section
    'security.title': 'Security and privacy',
    'security.description': 'We care about your privacy',
    'security.login': 'Authorization through Telegram',
    'security.no_password': 'The system is only accessible through the official Telegram widget. We never request your Telegram account password.',          
    'security.no_data': 'Safe data storage',
    'security.no_data_description': 'We do not store user passwords. API keys are stored in encrypted form and are used only for working with your channels.',
    'security.transparency': 'Transparency',
    'security.transparency_description': 'You always have full control over your data and can delete your account and all associated data at any time.',
    'security.protection': 'Certified protection',
    'security.protection_description': 'All information is transmitted over a secure HTTPS connection. Our service regularly undergoes security audits.',

    // Call to Action
    'call_to_action.title': 'Start using TelePublisher today',
    'call_to_action.description': 'Join thousands of channel administrators who have already simplified their work with our service.',
    'call_to_action.start_free': 'Start for free',

    // Footer
    'footer.description': 'Professional tool for creating, managing and publishing content in Telegram channels.',
    'footer.product': 'Product',
    'footer.company': 'Company',
    'footer.features': 'Features',
    'footer.pricing': 'Pricing',
    'footer.about': 'About',
    'footer.contact': 'Contact',
    'footer.legal_info': 'Legal information',
    'footer.terms_of_service': 'Terms of service',
    'footer.privacy_policy': 'Privacy policy',
    'footer.copyright': 'All rights reserved.',

    // Login Page
    'login.title': 'TelePublisher',
    'login.subtitle': 'Content management system for Telegram channels',
    'login.heading': 'Sign in',
    'login.error': 'Login error. Please try again.',
    'login.switch_account': 'Switch Account',
    'login.switch_account_description': 'To switch accounts, follow the link below. This will open Telegram where you can choose another account.',
    'login.direct_login': 'Sign in with another Telegram account',
    'login.back_to_normal': 'Back to normal login',
    'login.terms_agreement': 'By clicking the button, you agree to the terms of service',
    'login.loading': 'Loading...',

    // Dashboard Page
    'dashboard.title': 'Content Management',
    'dashboard.subtitle': 'Create, edit, and publish content to Telegram channels',
    'dashboard.tab_content': 'Content Generation',
    'dashboard.tab_channels': 'Channel Management',
    'dashboard.tab_instructions': 'Instructions',
    'dashboard.tab_subscription': 'Subscription',
    'dashboard.tab_content_short': 'Content',
    'dashboard.tab_channels_short': 'Channels',
    'dashboard.tab_instructions_short': 'Guide',
    'dashboard.tab_subscription_short': 'Sub',
    'dashboard.tab_scheduled': 'Scheduled Posts',
    'dashboard.tab_scheduled_short': 'Scheduled',
    'dashboard.tab_content_post': 'Post',
    'dashboard.tab_content_poll': 'Poll',

    // Content Generator
    'content_generator.title': 'Content Generator',
    'content_generator.prompt_label': 'Enter prompt',
    'content_generator.prompt_placeholder': 'What content should be generated?',
    'content_generator.generate_text': 'Generate text',
    'content_generator.generate_image': 'Generate image',
    'content_generator.generate_tags': 'Generate tags',
    'content_generator.credits': 'credit',
    'content_generator.credits_plural': 'credits',
    'content_generator.generation_results': 'Generation results:',
    'content_generator.text': 'Text:',
    'content_generator.image': 'Image:',
    'content_generator.tags': 'Tags:',
    'content_generator.error_text': 'Error generating text',
    'content_generator.error_image': 'Error generating image',
    'content_generator.error_tags': 'Error generating tags',
    'content_generator.error_text_from_image': 'Error generating text from image',
    'content_generator.error_image_from_image': 'Error generating image from reference',
    'content_generator.use_text': 'Use this text',
    'content_generator.use_image': 'Use this image',
    'content_generator.use_tags': 'Use these tags',
    'content_generator.text_copied': 'Text copied to publication panel',
    'content_generator.image_copied': 'Image copied to publication panel',
    'content_generator.tags_copied': 'Tags copied to publication panel',
    'content_generator.standard_mode': 'Standard',
    'content_generator.image_based_mode': 'Based on image',
    'content_generator.upload_image_prompt': 'Upload an image to generate content',
    'content_generator.additional_instructions': 'Additional instructions (optional)',
    'content_generator.describe_based_on_image': 'Describe what you want to generate based on the image...',
    'content_generator.generate_text_from_image': 'Generate text from image',
    'content_generator.generate_image_from_image': 'Generate new image',
    'content_generator.credits_visionapi': 'credits',
    'content_generator.credits_imageedit': 'credits',
    'content_generator.supported_formats': 'Supported formats',
    'content_generator.max_file_size': 'Maximum file size',
    'content_generator.conversion_note': 'Images will be automatically converted to PNG format for OpenAI processing.',
    'content_generator.start_recording': 'Start voice recording',
    'content_generator.stop_recording': 'Stop voice recording',
    'content_generator.recording': 'Recording in progress...',
    'content_generator.recording_in_progress': 'Recording in progress... Speak clearly.',
    'content_generator.recording_stopped': 'Recording stopped, processing speech...',
    'content_generator.speech_recognition_error': 'Speech recognition error. Please try again.',
    'content_generator.speech_not_supported': 'Speech recognition is not supported in your browser.',
    'content_generator.speech_recognition_lang': 'en-US',
    'content_generator.no_speech_detected': 'No speech was detected. Please try again.',
    'content_generator.audio_capture_error': 'Could not access the microphone. Please check your device settings.',
    'content_generator.microphone_permission_denied': 'Microphone access was denied. Please allow access to your microphone.',
    'content_generator.language_not_supported': 'The selected language is not supported for speech recognition on this device.',

    // Publish Panel
    'publish_panel.title': 'Publication Panel',
    'publish_panel.select_channel': 'Select channel',
    'publish_panel.select_channels': 'Select channels',
    'publish_panel.select_channel_error': 'Select a channel',
    'publish_panel.no_channel_error': 'Select a channel for publication',
    'publish_panel.no_content_error': 'Add text or image for publication',
    'publish_panel.text_label': 'Publication text',
    'publish_panel.text_placeholder': 'Enter publication text...',
    'publish_panel.image_url': 'Image URL',
    'publish_panel.image_url_placeholder': 'https://example.com/image.jpg',
    'publish_panel.tags': 'Tags',
    'publish_panel.image_preview': 'Image preview',
    'publish_panel.publish_button': 'Publish',
    'publish_panel.clear_fields': 'Clear all fields',
    'publish_panel.voice_input': 'Voice input',
    'publish_panel.voice_input_active': 'Voice input active',
    'publish_panel.voice_input_tooltip': 'Click to add text using voice input',
    'publish_panel.multiple_selection_hint': 'Click to open dropdown and select multiple channels',
    'publish_panel.publish_to_multiple': 'Publish to {count} channels',
    'publish_panel.schedule_to_multiple': 'Schedule to {count} channels',
    'publish_panel.publishing_progress': 'Publishing Progress',
    'publish_panel.channels': 'channels',
    'publish_panel.success_publish': 'Successfully published to:',
    'publish_panel.failed_publish': 'Failed to publish to:',
    'publish_panel.telegram_preview': 'Telegram Preview',
    'publish_panel.schedule_label': 'Scheduling',
    'publish_panel.publish_now': 'Publish now',
    'publish_panel.schedule_for_later': 'Schedule for later',
    'publish_panel.select_date_time': 'Select date and time',
    'publish_panel.no_schedule_date_error': 'Please select a date and time for scheduling',
    'publish_panel.schedule_in_past_error': 'Date and time cannot be in the past',
    'publish_panel.past_date_error': 'The scheduled date cannot be in the past',
    'publish_panel.schedule_button': 'Schedule',
    'publish_panel.message_too_long': 'Message is too long. Telegram has a 4096 character limit for messages.',
    'publish_panel.characters_left': 'characters left',
    'publish_panel.approaching_limit': 'Message is approaching Telegram\'s character limit. {remaining} characters left.',
    'publish_panel.caption_limit': 'Caption limit',
    'publish_panel.characters': 'characters',
    'publish_panel.approaching_caption_limit': 'Image caption is approaching Telegram\'s limit. {remaining} characters left.',
    'publish_panel.including_tags': 'including tags',
    'publish_panel.message_limit': 'Message limit',
    'publish_panel.error_chat_not_found': 'Error: Chat not found. Make sure the channel exists and the bot has access to it.',
    'publish_panel.error_bot_kicked': 'Error: Bot was kicked from the channel. Please add the bot back to the channel.',
    'publish_panel.error_not_enough_rights': 'Error: Bot does not have enough rights. Make sure the bot is an administrator with posting rights.',
    'publish_panel.error_bot_not_member': 'Error: Bot is not a member of the channel. Please add the bot to the channel as administrator.',
    'publish_panel.error_bot_cant': 'Error: Bot cannot perform this action. Check bot permissions in the channel.',
    'publish_panel.error_forbidden': 'Error: Action forbidden. The bot doesn\'t have permission to perform this action.',
    'publish_panel.error_permission_denied': 'Error: Permission denied. The bot doesn\'t have permission to perform this action.',
    'publish_panel.success_published': 'Successfully published to channel {channel}',
    'publish_panel.success_scheduled': 'Post scheduled in channel {channel} for {date}',
    'publish_panel.scheduled_success': 'Successfully scheduled for channel {channel} on {date}',
    'publish_panel.error_channel_not_found': 'Channel not found or bot token is missing',
    'publish_panel.error_scheduling': 'Error scheduling publication. Please try again.',
    'publish_panel.error_caption_too_long': 'Error: Image caption is too long. Telegram has a 1024 character limit for image captions.',
    'publish_panel.image_mode': 'Image Mode',
    'publish_panel.single_image': 'Single Image',
    'publish_panel.multiple_images': 'Multiple Images',
    'publish_panel.gallery_view': 'Gallery View',
    'publish_panel.album_preview': 'Album Preview',
    'publish_panel.image_count': '{count} images selected',
    'publish_panel.add_more_images': 'Add more images',
    'publish_panel.max_10_images': 'Maximum 10 images per post',
    'publish_panel.telegram_album': 'Telegram Album',
    'publish_panel.telegram_album_description': 'Images will be published as an album in Telegram',
    'publish_panel.first_image_caption': 'Only the first image will display the caption',
    'publish_panel.error_too_many_images': 'Error: Too many images selected. Telegram allows a maximum of 10 images per post.',
    'publish_panel.upload_progress': 'Uploading image {current} of {total}',
    'publish_panel.upload_complete': 'All images uploaded successfully',
    'publish_panel.scheduled_album': 'Album scheduled for {date}',
    'publish_panel.scheduled_multiple_images': 'Multiple images scheduled',
    'publish_panel.edit_scheduled_album': 'Edit scheduled album',
    'publish_panel.published_success': 'Successfully published',
    'publish_panel.published_failed': 'Failed to publish',

    // Image Uploader
    'image_uploader.label': 'Image',
    'image_uploader.url_mode': 'URL',
    'image_uploader.upload_mode': 'Upload',
    'image_uploader.url_placeholder': 'https://example.com/image.jpg',
    'image_uploader.drag_drop': 'Drag and drop an image here',
    'image_uploader.drag_single': 'Drag & drop image here or click to select',
    'image_uploader.or': 'or',
    'image_uploader.browse_files': 'Browse files',
    'image_uploader.max_size': 'PNG, JPG, GIF up to 10MB',
    'image_uploader.paste_hint': 'You can also paste images from clipboard (Ctrl+V)',
    'image_uploader.hosted_by': 'Images uploaded via TelePublisher',
    'image_uploader.uploading': 'Uploading',
    'image_uploader.change_image': 'Change',
    'image_uploader.remove': 'Remove',
    'image_uploader.error_not_image': 'The file is not an image',
    'image_uploader.error_too_large': 'The file is too large (max 10MB)',
    'image_uploader.error_upload_failed': 'Failed to upload image',
    
    // Multiple Image Uploader
    'image_uploader.label_multiple': 'Upload Images (max 10)',
    'image_uploader.drag_multiple': 'Drag & drop images here or click to select',
    'image_uploader.max_count_message': 'You can upload up to 10 images',
    'image_uploader.supported_formats': 'JPEG, PNG, GIF, WebP',
    'image_uploader.clear_all': 'Clear all images',
    'image_uploader.remove_image': 'Remove image',
    'image_uploader.max_images_reached': 'Maximum of 10 images allowed',
    'image_uploader.multiple_url_not_supported': 'URL mode with multiple images is not supported. Please use upload mode for multiple images.',
    'image_uploader.error_empty_url': 'Please enter an image URL',
    'image_uploader.error_invalid_url': 'Please enter a valid URL (e.g., https://example.com/image.jpg)',
    'image_uploader.add_url': 'Add',
    'image_uploader.url_hint': "Enter the URL of an image and click 'Add' or press Enter",

    // Alert component
    'alert.success_title': 'Success!',
    'alert.error_title': 'Error!',
    'alert.warning_title': 'Warning!',
    'alert.info_title': 'Information',
    'common.close': 'Close',

    // TagInput component
    'tag_input.placeholder': 'Add tag...',
    'tag_input.hint': 'Press Enter or comma to add a tag',
    'tag_input.remove_tag': 'Remove tag',

    // Channels Manager
    'channels_manager.title': 'Channel Management',
    'channels_manager.add_new_channel': 'Add new channel',
    'channels_manager.channel_username': '@channel username',
    'channels_manager.bot_token': 'Bot token',
    'channels_manager.add_channel': 'Add channel',
    'channels_manager.connected_channels': 'Connected channels:',
    'channels_manager.no_connected_channels': 'No connected channels',
    'channels_manager.token_configured': 'Token configured',
    'channels_manager.token_not_configured': 'Token not configured',
    'channels_manager.change_token': 'Change token',
    'channels_manager.add_token': 'Add token',
    'channels_manager.delete': 'Delete',
    'channels_manager.delete_channel': 'Delete channel',
    'channels_manager.delete_confirmation': 'Are you sure you want to delete channel "{0}"? This action cannot be undone.',
    'channels_manager.confirm_delete': 'Delete',
    'channels_manager.cancel': 'Cancel',
    'channels_manager.token_setup': 'Token setup for channel "{0}"',
    'channels_manager.enter_token': 'Enter Telegram bot token for this channel:',
    'channels_manager.save': 'Save',
    'channels_manager.error_username': 'Enter channel username',
    'channels_manager.error_already_added': 'Channel with this name is already added',
    'channels_manager.error_add_failed': 'Failed to add channel',
    'channels_manager.error_save_token': 'Failed to save token',
    'channels_manager.error_delete_channel': 'Failed to delete channel',
    'channels_manager.channels_limit': 'Channels: {0} of {1}',
    'channels_manager.unlimited_channels': 'Channels: Unlimited',
    'channels_manager.limit_reached': 'Channel limit reached',
    'channels_manager.error_limit_reached': 'Channel limit reached for your subscription',
    'channels_manager.upgrade_subscription': 'To add more channels, please upgrade your subscription',

    // Bot Instructions Panel
    'instructions.bot_title': 'Bot Creation Instructions',
    'instructions.service_title': 'TelePublisher Service Instructions',
    'instructions.collapse': 'Collapse instructions',
    'instructions.service_description': 'TelePublisher is a service for managing content in Telegram channels. Here\'s a brief instruction on how to use our service:',
    'instructions.getting_started': 'Getting Started',
    'instructions.getting_started_step_1': 'Create a Telegram bot via BotFather (see instructions below)',
    'instructions.getting_started_step_2': 'Add your Telegram channel in the "Channel Management" section',
    'instructions.getting_started_step_3': 'Specify the bot token for your channel',
    'instructions.getting_started_step_4': 'Make sure the bot is added to the channel as an administrator',
    'instructions.content_creation': 'Content Creation',
    'instructions.content_creation_step_1': 'Go to the "Content Generation" tab',
    'instructions.content_creation_step_2': 'Use the editor to create a new post',
    'instructions.content_creation_step_3': 'You can format text, add emojis and media files',
    'instructions.content_creation_step_4': 'Post preview is available on the right side of the screen',
    'instructions.publishing': 'Publishing and Scheduling',
    'instructions.publishing_step_1': 'Select a channel for publication in the right panel',
    'instructions.publishing_step_2': 'For instant publication, click "Publish Now"',
    'instructions.publishing_step_3': 'To schedule a publication, select the date and time, then click "Schedule"',
    'instructions.publishing_step_4': 'Scheduled publications can be edited and canceled before sending',
    'instructions.channel_management': 'Channel Management',
    'instructions.channel_management_step_1': 'Go to the "Channel Management" tab',
    'instructions.channel_management_step_2': 'Add a new channel by specifying its username',
    'instructions.channel_management_step_3': 'A bot token must be configured for each channel',
    'instructions.channel_management_step_4': 'You can manage multiple channels simultaneously (limit depends on your subscription plan)',
    'instructions.usage_tips': 'Usage Tips',
    'instructions.usage_tips_item_1': 'Use different bots for different channels to enhance security',
    'instructions.usage_tips_item_2': 'Plan content in advance to ensure regular publications',
    'instructions.usage_tips_item_3': 'Use the preview function before publishing to ensure correct display',
    'instructions.usage_tips_item_4': 'Paid plans offer more channels and extended functionality',
    'instructions.questions': 'If you have any questions',
    'instructions.support_text': 'Contact our support team via Telegram:',
    
    'instructions.bot_desc': 'To publish posts in Telegram channels, you need to create a bot and get its token. Follow the instructions below:',
    'instructions.step1_title': 'Open BotFather in Telegram',
    'instructions.step1_desc': 'Go to the official Telegram bot for creating other bots',
    'instructions.open_botfather': 'Open BotFather',
    'instructions.step2_title': 'Send a command to create a new bot',
    'instructions.step2_desc': 'BotFather will ask you to set a name and username for the bot.',
    'instructions.step3_title': 'Save the API token',
    'instructions.step3_desc': 'After creating the bot, you will receive an API token that looks something like this:',
    'instructions.step3_note': 'You will need this token to configure the channel in our system.',
    'instructions.step4_title': 'Add the bot to your channel as an administrator',
    'instructions.step4_desc': 'Open the channel settings, go to "Administrators" and add your bot, giving it permission to publish messages. Use only the mobile version of Telegram to add a bot to a channel',
    'instructions.step5_title': 'Enter the bot token in the channel settings',
    'instructions.step5_desc': 'In the "Channel Management" section, add your Telegram channel and specify the bot token you received from BotFather.',
    'instructions.security_title': 'Security Recommendations',
    'instructions.security_tip_1': 'Never share your bot token with third parties',
    'instructions.security_tip_2': 'Use a separate bot for each channel',
    'instructions.security_tip_3': 'Regularly check the activity of your bots',
    'instructions.security_tip_4': 'If you suspect token compromise, create a new bot',

    // Subscription Manager
    'subscription.title': 'Subscription Management',
    'subscription.current_plan': 'Current plan',
    'subscription.credits_available': 'Available credits: {0} of {1}',
    'subscription.total_used': 'Total used: {0} credits',
    'subscription.reset_date': 'Credits reset on {0}',
    'subscription.active_until': 'Subscription active until {0}',
    'subscription.cancelled': 'Subscription cancelled',
    'subscription.cancel_notice': 'Your subscription will be active until {0}, after which it will automatically downgrade to the free plan. Your accumulated credits will be preserved.',
    'subscription.free': 'Free',
    'subscription.standard': 'Standard',
    'subscription.business': 'Business',
    'subscription.free_price': '$0',
    'subscription.standard_price': '$10',
    'subscription.business_price': '$30',
    'subscription.month': 'month',
    'subscription.popular': 'POPULAR',
    'subscription.free_features_1': '10 AI credits per month',
    'subscription.free_features_2': 'Up to 2 channels',
    'subscription.free_features_3': 'Basic tools',
    'subscription.free_features_4': '2-10 trial publications',
    'subscription.standard_features_1': '100 AI credits per month',
    'subscription.standard_features_2': 'Up to 10 channels',
    'subscription.standard_features_3': 'Up to 100 publications',
    'subscription.standard_features_4': 'Priority support',
    'subscription.business_features_1': '400 AI credits per month',
    'subscription.business_features_2': 'Unlimited number of channels',
    'subscription.business_features_3': 'Up to 400 publications',
    'subscription.business_features_4': 'Dedicated support 24/7',
    'subscription.current_plan_button': 'Current plan',
    'subscription.subscribe_button': 'Subscribe',
    'subscription.manage_payments': 'Manage Payments',
    'subscription.cancel_subscription': 'Cancel Subscription',
    'subscription.renew_subscription': 'Renew Subscription',
    'subscription.loading': 'Loading...',
    'subscription.cancelling': 'Cancelling...',
    'subscription.payment_success': 'Payment successful! Your subscription has been activated.',
    'subscription.payment_cancelled': 'Payment was cancelled.',
    'subscription.error_load': 'Failed to load subscription information',
    'subscription.error_payment': 'Failed to create payment session',
    'subscription.test_mode_warning': 'Test mode detected: Your subscription may be updated without completing payment.',
    'subscription.continue_to_payment_confirm': 'Your plan was already updated in test mode. Do you still want to proceed to the payment page?',
    'subscription.payment_processed_not_updated': 'Payment was processed but subscription not updated. Please contact support.',

    // NotFoundPage
    'not_found.message': 'Page not found',
    'not_found.back_home': 'Back to home',
    
    // Poll Publisher
    'poll_publish.title': 'Create Poll',
    'poll_publish.question_label': 'Poll Question',
    'poll_publish.question_placeholder': 'Enter your poll question',
    'poll_publish.question_required': 'Poll question is required',
    'poll_publish.options_label': 'Poll Options',
    'poll_publish.option_placeholder': 'Option',
    'poll_publish.options_help': 'Minimum 2, maximum 10 options',
    'poll_publish.add_option': 'Add Option',
    'poll_publish.min_two_options': 'Poll must have at least 2 options with text',
    'poll_publish.settings_label': 'Poll Settings',
    'poll_publish.anonymous_label': 'Anonymous voting',
    'poll_publish.multiple_label': 'Allow multiple answers',
    
    // Poll Preview
    'poll_preview.title': 'Telegram Poll Preview',
    'poll_preview.question_placeholder': 'Your poll question will appear here',
    'poll_preview.options_placeholder': 'Add at least two options to see the preview',
    'poll_preview.anonymous': 'Anonymous',
    'poll_preview.not_anonymous': 'Not anonymous',
    'poll_preview.multiple_answers': 'Multiple answers',
    'poll_preview.single_answer': 'Single answer',
    'poll_preview.no_votes': '0 votes',

    // Post Preview
    'post_preview.title': 'Telegram Post Preview',

    // Scheduled Posts
    'scheduled_posts.title': 'Scheduled Posts',
    'scheduled_posts.date': 'Date',
    'scheduled_posts.channel': 'Channel',
    'scheduled_posts.content': 'Content',
    'scheduled_posts.type': 'Type',
    'scheduled_posts.actions': 'Actions',
    'scheduled_posts.edit': 'Edit',
    'scheduled_posts.delete': 'Delete',
    'scheduled_posts.no_posts': 'No scheduled posts found',
    'scheduled_posts.loading': 'Loading scheduled posts...',
    'scheduled_posts.confirm_delete': 'Are you sure you want to delete this scheduled post?',
    'scheduled_posts.delete_success': 'Post has been deleted from the schedule',
    'scheduled_posts.error_delete': 'Failed to delete scheduled post',
    'scheduled_posts.error_fetch': 'Failed to load scheduled posts',
    'scheduled_posts.error_fetch_single': 'Failed to load scheduled post',
    'scheduled_posts.scheduled_for': 'Scheduled for',
    'scheduled_posts.back': 'Back',
    'scheduled_posts.back_to_list': 'Back to list',
    'scheduled_posts.confirm_publish_now': 'Are you sure you want to publish this post now?',
    'scheduled_posts.publish_now': 'Publish now',
    'scheduled_posts.publish_success': 'Post has been published',
    'scheduled_posts.error_publish': 'Failed to publish post',
    'scheduled_posts.edit_title': 'Edit Scheduled Post',
    'scheduled_posts.delete_confirm_title': 'Delete Scheduled Post',
    'scheduled_posts.text_only': 'Text only',
    'scheduled_posts.image': 'Image',
    'scheduled_posts.album': 'Album',
    'scheduled_posts.poll': 'Poll',
    'scheduled_posts.poll_edit_not_available': 'Poll editing is not yet available',
    'publish_panel.update_success': 'Post has been updated successfully',
    'publish_panel.error_updating': 'Failed to update post',

    // Tokens translations for English
    'tokens.title': 'Purchase AI Tokens',
    'tokens.description': 'Boost your AI capabilities with additional tokens. These tokens can be used for AI-powered content generation, image creation, and other AI features.',
    'tokens.small_package': '100 AI Tokens',
    'tokens.small_description': 'Perfect for casual users',
    'tokens.large_package': '400 AI Tokens',
    'tokens.large_description': 'Best value for regular users',
    'tokens.includes': 'Includes {count} AI tokens',
    'tokens.buy_button': 'Purchase Tokens',
    'tokens.note': 'Note: Purchased tokens will be added to your account immediately after payment and do not expire.',
    'tokens.purchase_success': 'Tokens purchased successfully!',
    'tokens.error_purchase': 'Error processing token purchase',

    // Crypto payment translations
    'crypto.title': 'Cryptocurrency Payments',
    'crypto.available': 'Cryptocurrency payments available',
    'crypto.description': 'To pay with Bitcoin, Ethereum or other cryptocurrencies, please contact us through our Telegram channel.',
    'crypto.contact_button': 'Contact us on Telegram',
    'crypto.benefits': 'Benefits of crypto payments: lower fees, faster international transactions, and enhanced privacy.',

    // Scheduled Posts - Calendar View
    'scheduled_posts.calendar_view': 'Calendar View',
    'scheduled_posts.list_view': 'List View',
    'scheduled_posts.post_details': 'Post Details',
    'scheduled_posts.poll_details': 'Poll Details',
    'scheduled_posts.question': 'Question',
    'scheduled_posts.options': 'Options',
    
    // Calendar translations
    'calendar.today': 'Today',
    'calendar.previous': 'Previous',
    'calendar.next': 'Next',
    'calendar.month': 'Month',
    'calendar.week': 'Week',
    'calendar.day': 'Day',
    'calendar.agenda': 'Agenda',
    'calendar.date': 'Date',
    'calendar.time': 'Time',
    'calendar.event': 'Event',
    'calendar.no_events': 'No events in this range',

    // Drafts translations
    'dashboard.tab_content_drafts': 'Drafts',
    'drafts.title': 'My Drafts',
    'drafts.subtitle': 'Save and organize your content drafts, templates, and ideas',
    'drafts.no_drafts': 'No drafts found',
    'drafts.create_new': 'Create New Draft',
    'drafts.search': 'Search drafts...',
    'drafts.filter_all': 'All',
    'drafts.filter_with_images': 'With Images',
    'drafts.filter_text_only': 'Text Only',
    'drafts.sort_newest': 'Newest',
    'drafts.sort_oldest': 'Oldest',
    'drafts.sort_alphabetical': 'Alphabetical',
    'drafts.edit': 'Edit',
    'drafts.delete': 'Delete',
    'drafts.copy_to_post': 'Copy to Post',
    'drafts.copy_to_poll': 'Copy to Poll',
    'drafts.created_on': 'Created: {date}',
    'drafts.updated_on': 'Updated: {date}',
    'drafts.confirm_delete': 'Are you sure you want to delete this draft?',
    'drafts.confirm_delete_description': 'This action cannot be undone.',
    'drafts.delete_success': 'Draft has been deleted',
    'drafts.create_success': 'Draft has been created',
    'drafts.update_success': 'Draft has been updated',
    'drafts.error_create': 'Failed to create draft',
    'drafts.error_update': 'Failed to update draft',
    'drafts.error_delete': 'Failed to delete draft',
    'drafts.error_loading': 'Failed to load drafts',
    'drafts.copied_to_editor': 'Draft copied to editor',
    'drafts.editor_title': 'Draft Editor',
    'drafts.editor_title_placeholder': 'Draft title',
    'drafts.editor_content_placeholder': 'Write your content here...',
    'drafts.save': 'Save Draft',
    'drafts.cancel': 'Cancel',
    'drafts.title_required': 'Title is required',
    'drafts.content_required': 'Content is required',
    'drafts.upload_image': 'Upload Image',
    'drafts.add_tags': 'Add Tags',
    'drafts.preview': 'Preview',
    'drafts.editor': 'Editor',

    // Image position translations
    'publish_panel.image_position': 'Image Position',
    'publish_panel.image_position_top': 'Top',
    'publish_panel.image_position_bottom': 'Bottom',
    'publish_panel.image_position_top_description': 'Image will be shown at the top of the post',
    'publish_panel.image_position_bottom_description': 'Image will be shown at the bottom of the post',
    'publish_panel.image_position_help': 'Position determines where the image appears in the post',
    'publish_panel.bottom_position_single_image': 'Bottom position supports only single image',
    'publish_panel.multiple_images_note': '[Multiple images]',
    
    // Inline buttons translations
    'publish_panel.inline_buttons': 'Inline Buttons',
    'publish_panel.add_button': 'Add Button',
    'publish_panel.button_text': 'Button Text',
    'publish_panel.button_url': 'Button URL',
    'publish_panel.button_text_placeholder': 'Click here',
    'publish_panel.button_url_placeholder': 'https://example.com',
    'publish_panel.remove_button': 'Remove',
    'publish_panel.max_buttons': 'Maximum 5 buttons allowed',
    'publish_panel.button_text_required': 'Button text is required',
    'publish_panel.button_url_required': 'Button URL is required',
    'publish_panel.button_url_invalid': 'Please enter a valid URL',
    'publish_panel.buttons': 'Telegram Buttons',
    'publish_panel.buttons_note': 'Buttons will be displayed one below another at the bottom of your Telegram post.',
    'publish_panel.invalid_url': 'Please enter a valid URL (e.g., https://example.com)',
    'publish_panel.buttons_not_available_top': 'Buttons are not available when image position is set to Top. Change the image position to Bottom to use buttons.',
    'publish_panel.buttons_cleared': 'Buttons cleared',
    'publish_panel.buttons_cleared_description': 'Buttons were removed because they are not compatible with top image position.',
  },
  ru: {
    // Navbar
    'navbar.logout': 'Выйти',
    'navbar.credits': 'кредитов',
    'navbar.credit_info': 'Информация о кредитах',
    'navbar.subscription_type': 'Тип подписки',
    'navbar.total_used': 'Всего использовано',
    'navbar.reset_date': 'Дата обновления',
    'navbar.subscription_status': 'Статус подписки',
    'navbar.active': 'Активна',
    'navbar.inactive': 'Неактивна',
    'navbar.no_data': 'Нет данных',
    
    // Hero section
    'hero.title': 'TelePublisher',
    'hero.description': 'Профессиональная система управления контентом для Telegram-каналов. Создавайте, редактируйте и публикуйте контент с легкостью.',
    'hero.start_free': 'Начать бесплатно',
    'hero.learn_more': 'Узнать больше',

    // Features section
    'features.title': 'Наши возможности',
    'features.fast_publication': 'Быстрая публикация',
    'features.fast_publication_description': 'Публикуйте контент мгновенно или планируйте публикации на будущее время.',
    'features.multiple_channels': 'Множество каналов',
    'features.multiple_channels_description': 'Управляйте несколькими каналами с единой панели администратора.',
    'features.ai_content': 'AI-генерация контента',
    'features.ai_content_description': 'Создавайте качественный контент, изображения и хэштеги с помощью продвинутых ИИ-инструментов.',
    'features.content_management': 'Управление контентом',
    'features.easy_interface': 'Удобный интерфейс',
    'features.easy_interface_description': 'Интуитивно понятный интерфейс для комфортной работы с контентом.',
    'features.security': 'Безопасность',
    'features.security_description': 'Вход через Telegram без передачи паролей. Мы не храним чувствительных данных.',
    'features.privacy': 'Приватность',
    'features.privacy_description': 'Мы не собираем личную информацию и не передаем данные третьим лицам.',

    // Video section
    'video.title': 'TelePublisher в действии',
    'video.description': 'Посмотрите наш обучающий видеоролик, чтобы узнать, как оптимизировать ваш Telegram-канал с помощью наших инструментов',
    'video.channel_link': 'Посетите наш YouTube канал для просмотра других обучающих видео',

    // Pricing section
    'pricing.title': 'Тарифные планы',
    'pricing.free': 'Бесплатный',
    'pricing.free_channels': 'До 2 каналов',
    'pricing.basic-tools': 'Базовые инструменты',
    'pricing.free_publications': '2-10 пробных публикаций',
    'pricing.start-free': 'Начать бесплатно',
    'pricing.mounth': 'месяц',


    'pricing.popular': 'ПОПУЛЯРНЫЙ',
    'pricing.standard': 'Стандарт',
    'pricing.standard_channels': 'До 10 каналов',
    'pricing.standard_publications': 'До 100 публикаций',
    'pricing.standard_support': 'Приоритетная поддержка',
    'pricing.choose_plan': 'Выбрать план',


    'pricing.business': 'Бизнес',
    'pricing.business_channels': 'Неограниченное количество каналов',
    'pricing.business_publications': 'До 400 публикаций',
    'pricing.business_support': 'Выделенная поддержка 24/7',

    // Security Section
    'security.title': 'Безопасность и приватность',
    'security.description': 'Мы заботимся о вашей конфиденциальности',
    'security.login': 'Авторизация через Telegram',
    'security.no_password': 'Вход в систему осуществляется исключительно через официальный виджет Telegram. Мы никогда не запрашиваем ваш пароль от аккаунта Telegram.',          
    'security.no_data': 'Безопасное хранение данных',
    'security.no_data_description': 'Мы не храним пароли пользователей. Ключи API хранятся в зашифрованном виде и используются только для работы с вашими каналами.',
    'security.transparency': 'Прозрачность',
    'security.transparency_description': 'Вы всегда имеете полный контроль над своими данными и можете удалить аккаунт и все связанные с ним данные в любой момент.',
    'security.protection': 'Сертифицированная защита',
    'security.protection_description': 'Вся информация передается по защищенному HTTPS-соединению. Наш сервис регулярно проходит аудиты безопасности.',

    // Call to Action
    'call_to_action.title': 'Начните использовать TelePublisher сегодня',
    'call_to_action.description': 'Присоединяйтесь к тысячам администраторов каналов, которые уже упростили свою работу с помощью нашего сервиса.',
    'call_to_action.start_free': 'Зарегистрироваться бесплатно',

    // Footer
    'footer.description': 'Профессиональный инструмент для создания, управления и публикации контента в Telegram-каналах.',
    'footer.product': 'Продукт',
    'footer.company': 'Компания',
    'footer.features': 'Возможности',
    'footer.pricing': 'Тарифы',
    'footer.about': 'О нас',
    'footer.contact': 'Контакты',
    'footer.legal_info': 'Правовая информация',
    'footer.terms_of_service': 'Условия использования',
    'footer.privacy_policy': 'Политика конфиденциальности',
    'footer.copyright': 'Все права защищены.',

    // Login Page
    'login.title': 'TelePublisher',
    'login.subtitle': 'Система управления контентом для Telegram-каналов',
    'login.heading': 'Вход в систему',
    'login.error': 'Ошибка входа. Пожалуйста, попробуйте снова.',
    'login.switch_account': 'Сменить аккаунт',
    'login.switch_account_description': 'Для смены аккаунта перейдите по ссылке ниже. Это откроет Телеграм, где вы сможете выбрать другой аккаунт.',
    'login.direct_login': 'Войти с другим аккаунтом Telegram',
    'login.back_to_normal': 'Вернуться к обычному входу',
    'login.terms_agreement': 'Нажимая кнопку, вы соглашаетесь с условиями использования сервиса',
    'login.loading': 'Загрузка...',

    // Dashboard Page
    'dashboard.title': 'Управление контентом',
    'dashboard.subtitle': 'Создавайте, редактируйте и публикуйте контент в Telegram-каналы',
    'dashboard.tab_content': 'Генерация контента',
    'dashboard.tab_channels': 'Управление каналами',
    'dashboard.tab_instructions': 'Инструкция',
    'dashboard.tab_subscription': 'Подписка',
    'dashboard.tab_content_short': 'Контент',
    'dashboard.tab_channels_short': 'Каналы',
    'dashboard.tab_instructions_short': 'Гид',
    'dashboard.tab_subscription_short': 'Тариф',
    'dashboard.tab_scheduled': 'Запланированные публикации',
    'dashboard.tab_scheduled_short': 'Запланированные',
    'dashboard.tab_content_post': 'Пост',
    'dashboard.tab_content_poll': 'Опрос',

    // Content Generator
    'content_generator.title': 'Генератор контента',
    'content_generator.prompt_label': 'Введите промпт',
    'content_generator.prompt_placeholder': 'О чем сгенерировать контент?',
    'content_generator.generate_text': 'Сгенерировать текст',
    'content_generator.generate_image': 'Сгенерировать изображение',
    'content_generator.generate_tags': 'Сгенерировать теги',
    'content_generator.credits': 'кредит',
    'content_generator.credits_plural': 'кредита',
    'content_generator.generation_results': 'Результат генерации:',
    'content_generator.text': 'Текст:',
    'content_generator.image': 'Изображение:',
    'content_generator.tags': 'Теги:',
    'content_generator.error_text': 'Ошибка при генерации текста',
    'content_generator.error_image': 'Ошибка при генерации изображения',
    'content_generator.error_tags': 'Ошибка при генерации тегов',
    'content_generator.error_text_from_image': 'Ошибка при генерации текста по изображению',
    'content_generator.error_image_from_image': 'Ошибка при генерации изображения на основе референса',
    'content_generator.use_text': 'Использовать этот текст',
    'content_generator.use_image': 'Использовать это изображение',
    'content_generator.use_tags': 'Использовать эти теги',
    'content_generator.text_copied': 'Текст скопирован в панель публикации',
    'content_generator.image_copied': 'Изображение скопировано в панель публикации',
    'content_generator.tags_copied': 'Теги скопированы в панель публикации',
    'content_generator.standard_mode': 'Стандартный',
    'content_generator.image_based_mode': 'На основе изображения',
    'content_generator.upload_image_prompt': 'Загрузите изображение для генерации контента',
    'content_generator.additional_instructions': 'Дополнительные инструкции (необязательно)',
    'content_generator.describe_based_on_image': 'Опишите, что вы хотите получить на основе изображения...',
    'content_generator.generate_text_from_image': 'Генерировать текст из изображения',
    'content_generator.generate_image_from_image': 'Генерировать новое изображение',
    'content_generator.credits_visionapi': 'кредита',
    'content_generator.credits_imageedit': 'кредита',
    'content_generator.supported_formats': 'Поддерживаемые форматы',
    'content_generator.max_file_size': 'Максимальный размер файла',
    'content_generator.conversion_note': 'Изображения будут автоматически конвертированы в формат PNG для обработки OpenAI.',
    'content_generator.start_recording': 'Начать голосовой ввод',
    'content_generator.stop_recording': 'Остановить запись',
    'content_generator.recording': 'Идёт запись...',
    'content_generator.recording_in_progress': 'Идёт запись... Говорите чётко.',
    'content_generator.recording_stopped': 'Запись остановлена, обрабатываю речь...',
    'content_generator.speech_recognition_error': 'Ошибка распознавания речи. Пожалуйста, попробуйте снова.',
    'content_generator.speech_not_supported': 'Распознавание речи не поддерживается в вашем браузере.',
    'content_generator.speech_recognition_lang': 'ru-RU',
    'content_generator.no_speech_detected': 'Голос не обнаружен. Пожалуйста, попробуйте снова.',
    'content_generator.audio_capture_error': 'Не удалось получить доступ к микрофону. Проверьте настройки устройства.',
    'content_generator.microphone_permission_denied': 'Доступ к микрофону запрещен. Пожалуйста, разрешите доступ к микрофону.',
    'content_generator.language_not_supported': 'Выбранный язык не поддерживается для распознавания речи на этом устройстве.',

    // Publish Panel
    'publish_panel.title': 'Панель публикации',
    'publish_panel.select_channel': 'Выберите канал',
    'publish_panel.select_channels': 'Выберите каналы',
    'publish_panel.select_channel_error': 'Выберите канал',
    'publish_panel.no_channel_error': 'Выберите канал для публикации',
    'publish_panel.no_content_error': 'Добавьте текст или изображение для публикации',
    'publish_panel.text_label': 'Текст публикации',
    'publish_panel.text_placeholder': 'Введите текст публикации...',
    'publish_panel.image_url': 'URL изображения',
    'publish_panel.image_url_placeholder': 'https://example.com/image.jpg',
    'publish_panel.tags': 'Теги',
    'publish_panel.image_preview': 'Предпросмотр изображения',
    'publish_panel.publish_button': 'Опубликовать',
    'publish_panel.clear_fields': 'Очистить все поля',
    'publish_panel.voice_input': 'Голосовой ввод',
    'publish_panel.voice_input_active': 'Голосовой ввод активен',
    'publish_panel.voice_input_tooltip': 'Нажмите, чтобы добавить текст с помощью голосового ввода',
    'publish_panel.multiple_selection_hint': 'Нажмите, чтобы открыть выпадающий список и выбрать несколько каналов',
    'publish_panel.publish_to_multiple': 'Опубликовать в {count} каналах',
    'publish_panel.schedule_to_multiple': 'Запланировать в {count} каналах',
    'publish_panel.publishing_progress': 'Прогресс публикации',
    'publish_panel.channels': 'каналов',
    'publish_panel.success_publish': 'Успешно опубликовано в:',
    'publish_panel.failed_publish': 'Не удалось опубликовать в:',
    'publish_panel.telegram_preview': 'Предпросмотр в Telegram',
    'publish_panel.schedule_label': 'Планирование',
    'publish_panel.publish_now': 'Опубликовать сейчас',
    'publish_panel.schedule_for_later': 'Запланировать',
    'publish_panel.select_date_time': 'Выберите дату и время',
    'publish_panel.no_schedule_date_error': 'Пожалуйста, выберите дату и время для планирования',
    'publish_panel.schedule_in_past_error': 'Дата и время не могут быть в прошлом',
    'publish_panel.past_date_error': 'Запланированная дата не может быть в прошлом',
    'publish_panel.schedule_button': 'Запланировать',
    'publish_panel.message_too_long': 'Сообщение слишком длинное. Telegram имеет ограничение в 4096 символов для сообщений.',
    'publish_panel.characters_left': 'символов осталось',
    'publish_panel.approaching_limit': 'Сообщение приближается к лимиту символов Telegram. Осталось {remaining} символов.',
    'publish_panel.caption_limit': 'Лимит подписи',
    'publish_panel.characters': 'символов',
    'publish_panel.approaching_caption_limit': 'Подпись к изображению приближается к лимиту Telegram. Осталось {remaining} символов.',
    'publish_panel.including_tags': 'включая теги',
    'publish_panel.message_limit': 'Лимит сообщения',
    'publish_panel.error_chat_not_found': 'Ошибка: Чат не найден. Убедитесь, что канал существует и бот имеет к нему доступ.',
    'publish_panel.error_bot_kicked': 'Ошибка: Бот был исключен из канала. Пожалуйста, добавьте бота обратно в канал.',
    'publish_panel.error_not_enough_rights': 'Ошибка: У бота недостаточно прав. Убедитесь, что бот является администратором с правами на публикацию.',
    'publish_panel.error_bot_not_member': 'Ошибка: Бот не является участником канала. Пожалуйста, добавьте бота в канал как администратора.',
    'publish_panel.error_bot_cant': 'Ошибка: Бот не может выполнить это действие. Проверьте права бота в канале.',
    'publish_panel.error_forbidden': 'Ошибка: Действие запрещено. У бота нет разрешения на выполнение этого действия.',
    'publish_panel.error_permission_denied': 'Ошибка: Отказано в доступе. У бота нет разрешения на выполнение этого действия.',
    'publish_panel.success_published': 'Успешно опубликовано в канале {channel}',
    'publish_panel.success_scheduled': 'Пост запланирован в канале {channel} на {date}',
    'publish_panel.scheduled_success': 'Успешно запланировано для канала {channel} на {date}',
    'publish_panel.error_channel_not_found': 'Канал не найден или отсутствует токен бота',
    'publish_panel.error_scheduling': 'Ошибка при планировании публикации. Пожалуйста, попробуйте снова.',
    'publish_panel.error_caption_too_long': 'Ошибка: Подпись изображения слишком длинная. Telegram имеет ограничение в 1024 символа для подписей изображений.',
    'publish_panel.image_mode': 'Режим изображения',
    'publish_panel.single_image': 'Одно изображение',
    'publish_panel.multiple_images': 'Несколько изображений',
    'publish_panel.gallery_view': 'Галерея',
    'publish_panel.album_preview': 'Предпросмотр альбома',
    'publish_panel.image_count': '{count} изображений выбрано',
    'publish_panel.add_more_images': 'Добавить еще изображения',
    'publish_panel.max_10_images': 'Максимум 10 изображений на пост',
    'publish_panel.telegram_album': 'Телеграм-альбом',
    'publish_panel.telegram_album_description': 'Изображения будут опубликованы как альбом в Telegram',
    'publish_panel.first_image_caption': 'Только первое изображение будет отображать подпись',
    'publish_panel.error_too_many_images': 'Ошибка: Слишком много изображений выбрано. Telegram позволяет максимум 10 изображений на пост.',
    'publish_panel.upload_progress': 'Загрузка изображения {current} из {total}',
    'publish_panel.upload_complete': 'Все изображения загружены успешно',
    'publish_panel.scheduled_album': 'Альбом запланирован на {date}',
    'publish_panel.scheduled_multiple_images': 'Несколько изображений запланировано',
    'publish_panel.edit_scheduled_album': 'Редактировать запланированный альбом',
    'publish_panel.published_success': 'Успешно опубликовано',
    'publish_panel.published_failed': 'Не удалось опубликовать',

    // Image Uploader
    'image_uploader.label': 'Изображение',
    'image_uploader.url_mode': 'Ссылка',
    'image_uploader.upload_mode': 'Загрузка',
    'image_uploader.url_placeholder': 'https://example.com/image.jpg',
    'image_uploader.drag_drop': 'Перетащите изображение сюда',
    'image_uploader.drag_single': 'Перетащите изображение сюда или нажмите для выбора',
    'image_uploader.or': 'или',
    'image_uploader.browse_files': 'Выберите файл',
    'image_uploader.max_size': 'PNG, JPG, GIF до 10МБ',
    'image_uploader.paste_hint': 'Вы также можете вставить изображения из буфера обмена (Ctrl+V)',
    'image_uploader.hosted_by': 'Изображения загружаются через TelePublisher',
    'image_uploader.uploading': 'Загрузка',
    'image_uploader.change_image': 'Изменить',
    'image_uploader.remove': 'Удалить',
    'image_uploader.error_not_image': 'Файл не является изображением',
    'image_uploader.error_too_large': 'Файл слишком большой (макс. 10МБ)',
    'image_uploader.error_upload_failed': 'Не удалось загрузить изображение',
    
    // Multiple Image Uploader
    'image_uploader.label_multiple': 'Загрузить изображения (макс. 10)',
    'image_uploader.drag_multiple': 'Перетащите изображения сюда или нажмите для выбора',
    'image_uploader.max_count_message': 'Вы можете загрузить до 10 изображений',
    'image_uploader.supported_formats': 'JPEG, PNG, GIF, WebP',
    'image_uploader.clear_all': 'Очистить все изображения',
    'image_uploader.remove_image': 'Удалить изображение',
    'image_uploader.max_images_reached': 'Максимум 10 изображений разрешено',
    'image_uploader.multiple_url_not_supported': 'Режим URL с несколькими изображениями не поддерживается. Пожалуйста, используйте режим загрузки для нескольких изображений.',
    'image_uploader.error_empty_url': 'Пожалуйста, введите URL изображения',
    'image_uploader.error_invalid_url': 'Пожалуйста, введите корректный URL (например, https://example.com/image.jpg)',
    'image_uploader.add_url': 'Добавить',
    'image_uploader.url_hint': 'Введите URL изображения и нажмите "Добавить" или Enter',

    // Alert component
    'alert.success_title': 'Успех!',
    'alert.error_title': 'Ошибка!',
    'alert.warning_title': 'Предупреждение!',
    'alert.info_title': 'Информация',
    'common.close': 'Закрыть',

    // TagInput component
    'tag_input.placeholder': 'Добавить тег...',
    'tag_input.hint': 'Нажмите Enter или запятую для добавления тега',
    'tag_input.remove_tag': 'Удалить тег',

    // Channels Manager
    'channels_manager.title': 'Управление каналами',
    'channels_manager.add_new_channel': 'Добавить новый канал',
    'channels_manager.channel_username': '@username канала',
    'channels_manager.bot_token': 'Токен бота',
    'channels_manager.add_channel': 'Добавить канал',
    'channels_manager.connected_channels': 'Подключенные каналы:',
    'channels_manager.no_connected_channels': 'Нет подключенных каналов',
    'channels_manager.token_configured': 'Токен настроен',
    'channels_manager.token_not_configured': 'Токен не настроен',
    'channels_manager.change_token': 'Изменить токен',
    'channels_manager.add_token': 'Добавить токен',
    'channels_manager.delete': 'Удалить',
    'channels_manager.delete_channel': 'Удаление канала',
    'channels_manager.delete_confirmation': 'Вы уверены, что хотите удалить канал "{0}"? Это действие нельзя отменить.',
    'channels_manager.confirm_delete': 'Удалить',
    'channels_manager.cancel': 'Отмена',
    'channels_manager.token_setup': 'Настройка токена для канала "{0}"',
    'channels_manager.enter_token': 'Введите токен Telegram бота для этого канала:',
    'channels_manager.save': 'Сохранить',
    'channels_manager.error_username': 'Введите имя пользователя канала',
    'channels_manager.error_already_added': 'Канал с таким именем уже добавлен',
    'channels_manager.error_add_failed': 'Не удалось добавить канал',
    'channels_manager.error_save_token': 'Не удалось сохранить токен',
    'channels_manager.error_delete_channel': 'Не удалось удалить канал',
    'channels_manager.channels_limit': 'Каналы: {0} из {1}',
    'channels_manager.unlimited_channels': 'Каналы: Без ограничений',
    'channels_manager.limit_reached': 'Достигнут лимит каналов',
    'channels_manager.error_limit_reached': 'Достигнут лимит каналов для вашей подписки',
    'channels_manager.upgrade_subscription': 'Для добавления большего числа каналов обновите подписку',

    // Bot Instructions Panel
    'instructions.bot_title': 'Инструкция по созданию бота',
    'instructions.service_title': 'Инструкция по использованию сервиса TelePublisher',
    'instructions.collapse': 'Свернуть инструкцию',
    'instructions.service_description': 'TelePublisher — это сервис для управления контентом в Telegram-каналах. Вот краткая инструкция, как использовать наш сервис:',
    'instructions.getting_started': 'Начало работы',
    'instructions.getting_started_step_1': 'Создайте Telegram бота через BotFather (см. инструкцию ниже)',
    'instructions.getting_started_step_2': 'Добавьте ваш Telegram-канал в разделе "Управление каналами"',
    'instructions.getting_started_step_3': 'Укажите токен бота для вашего канала',
    'instructions.getting_started_step_4': 'Убедитесь, что бот добавлен в канал как администратор',
    'instructions.content_creation': 'Создание контента',
    'instructions.content_creation_step_1': 'Перейдите во вкладку "Генерация контента"',
    'instructions.content_creation_step_2': 'Используйте редактор для создания нового поста',
    'instructions.content_creation_step_3': 'Вы можете форматировать текст, добавлять эмодзи и медиафайлы',
    'instructions.content_creation_step_4': 'Предварительный просмотр поста доступен в правой части экрана',
    'instructions.publishing': 'Публикация и планирование',
    'instructions.publishing_step_1': 'Выберите канал для публикации в панели справа',
    'instructions.publishing_step_2': 'Для мгновенной публикации нажмите "Опубликовать сейчас"',
    'instructions.publishing_step_3': 'Для планирования публикации выберите дату и время, затем нажмите "Запланировать"',
    'instructions.publishing_step_4': 'Запланированные публикации можно редактировать и отменять до момента отправки',
    'instructions.channel_management': 'Управление каналами',
    'instructions.channel_management_step_1': 'Перейдите во вкладку "Управление каналами"',
    'instructions.channel_management_step_2': 'Добавьте новый канал, указав его username',
    'instructions.channel_management_step_3': 'Для каждого канала необходимо настроить токен бота',
    'instructions.channel_management_step_4': 'Вы можете управлять несколькими каналами одновременно (лимит зависит от тарифного плана)',
    'instructions.usage_tips': 'Советы по использованию',
    'instructions.usage_tips_item_1': 'Используйте разные боты для разных каналов для повышения безопасности',
    'instructions.usage_tips_item_2': 'Планируйте контент заранее, чтобы обеспечить регулярность публикаций',
    'instructions.usage_tips_item_3': 'Используйте функцию предпросмотра перед публикацией, чтобы убедиться в корректном отображении',
    'instructions.usage_tips_item_4': 'В платных тарифах доступно больше каналов и расширенная функциональность',
    'instructions.questions': 'Если у вас возникли вопросы',
    'instructions.support_text': 'Свяжитесь с нашей службой поддержки через Telegram:',
    
    'instructions.bot_desc': 'Для публикации постов в Telegram-каналы вам необходимо создать бота и получить его токен. Следуйте инструкции ниже:',
    'instructions.step1_title': 'Откройте BotFather в Telegram',
    'instructions.step1_desc': 'Перейдите к официальному боту Telegram для создания других ботов',
    'instructions.open_botfather': 'Открыть BotFather',
    'instructions.step2_title': 'Отправьте команду для создания нового бота',
    'instructions.step2_desc': 'BotFather попросит вас задать имя и имя пользователя для бота.',
    'instructions.step3_title': 'Сохраните токен API',
    'instructions.step3_desc': 'После создания бота вы получите токен API, выглядящий примерно так:',
    'instructions.step3_note': 'Этот токен вам понадобится для настройки канала в нашей системе.',
    'instructions.step4_title': 'Добавьте бота в ваш канал как администратора',
    'instructions.step4_desc': 'Откройте настройки канала, перейдите в "Администраторы" и добавьте вашего бота, предоставив ему права на публикацию сообщений. Используйте только мобильную версию Telegram для добавления бота в канал',
    'instructions.step5_title': 'Введите токен бота в настройках канала',
    'instructions.step5_desc': 'В разделе "Управление каналами" добавьте ваш Telegram-канал и укажите токен бота, который вы получили от BotFather.',
    'instructions.security_title': 'Рекомендации по безопасности',
    'instructions.security_tip_1': 'Никогда не делитесь токеном бота с третьими лицами',
    'instructions.security_tip_2': 'Используйте отдельного бота для каждого канала',
    'instructions.security_tip_3': 'Регулярно проверяйте активность ваших ботов',
    'instructions.security_tip_4': 'При подозрении на компрометацию токена, создайте нового бота',

    // Subscription Manager
    'subscription.title': 'Управление подпиской',
    'subscription.current_plan': 'Текущий план',
    'subscription.credits_available': 'Доступно кредитов: {0} из {1}',
    'subscription.total_used': 'Использовано всего: {0} кредитов',
    'subscription.reset_date': 'Кредиты обновятся {0}',
    'subscription.active_until': 'Подписка активна до {0}',
    'subscription.cancelled': 'Подписка отменена',
    'subscription.cancel_notice': 'Ваша подписка будет действовать до {0}, после чего будет автоматически переведена на бесплатный план. Ваши накопленные кредиты будут сохранены.',
    'subscription.free': 'Бесплатный',
    'subscription.standard': 'Стандарт',
    'subscription.business': 'Бизнес',
    'subscription.free_price': '0 $',
    'subscription.standard_price': '10$',
    'subscription.business_price': '30$',
    'subscription.month': 'месяц',
    'subscription.popular': 'Популярный',
    'subscription.free_features_1': '10 AI-кредитов в месяц',
    'subscription.free_features_2': 'До 2 каналов',
    'subscription.free_features_3': 'Базовые инструменты',
    'subscription.free_features_4': '2-10 пробных публикаций',
    'subscription.standard_features_1': '100 AI-кредитов в месяц',
    'subscription.standard_features_2': 'До 10 каналов',
    'subscription.standard_features_3': 'До 100 публикаций',
    'subscription.standard_features_4': 'Приоритетная поддержка',
    'subscription.business_features_1': '400 AI-кредитов в месяц',
    'subscription.business_features_2': 'Неограниченное количество каналов',
    'subscription.business_features_3': 'До 400 публикаций',
    'subscription.business_features_4': 'Выделенная поддержка 24/7',
    'subscription.current_plan_button': 'Текущий тариф',
    'subscription.subscribe_button': 'Оформить подписку',
    'subscription.manage_payments': 'Управление платежами',
    'subscription.cancel_subscription': 'Отменить подписку',
    'subscription.renew_subscription': 'Возобновить подписку',
    'subscription.loading': 'Загрузка...',
    'subscription.cancelling': 'Отмена...',
    'subscription.payment_success': 'Оплата прошла успешно! Подписка активирована.',
    'subscription.payment_cancelled': 'Оплата была отменена.',
    'subscription.error_load': 'Не удалось загрузить информацию о подписке',
    'subscription.error_payment': 'Не удалось создать платежную сессию',
    'subscription.test_mode_warning': 'Обнаружен тестовый режим: подписка может быть обновлена без завершения оплаты.',
    'subscription.continue_to_payment_confirm': 'Ваш тариф уже был обновлен в тестовом режиме. Вы все еще хотите перейти на страницу оплаты?',
    'subscription.payment_processed_not_updated': 'Платеж обработан, но подписка не обновлена. Пожалуйста, обратитесь в службу поддержки.',

    // NotFoundPage
    'not_found.message': 'Страница не найдена',
    'not_found.back_home': 'Вернуться на главную',
    
    // Poll Publisher
    'poll_publish.title': 'Создать опрос',
    'poll_publish.question_label': 'Вопрос опроса',
    'poll_publish.question_placeholder': 'Введите вопрос опроса',
    'poll_publish.question_required': 'Необходимо ввести вопрос опроса',
    'poll_publish.options_label': 'Варианты ответов',
    'poll_publish.option_placeholder': 'Вариант',
    'poll_publish.options_help': 'Минимум 2, максимум 10 вариантов',
    'poll_publish.add_option': 'Добавить вариант',
    'poll_publish.min_two_options': 'Опрос должен содержать минимум 2 варианта ответа с текстом',
    'poll_publish.settings_label': 'Настройки опроса',
    'poll_publish.anonymous_label': 'Анонимное голосование',
    'poll_publish.multiple_label': 'Разрешить выбор нескольких вариантов',
    
    // Poll Preview
    'poll_preview.title': 'Предпросмотр опроса',
    'poll_preview.question_placeholder': 'Здесь будет отображаться вопрос опроса',
    'poll_preview.options_placeholder': 'Добавьте хотя бы два варианта ответа для предпросмотра',
    'poll_preview.anonymous': 'Анонимно',
    'poll_preview.not_anonymous': 'Не анонимно',
    'poll_preview.multiple_answers': 'Несколько ответов',
    'poll_preview.single_answer': 'Один ответ',
    'poll_preview.no_votes': '0 голосов',

    // Post Preview
    'post_preview.title': 'Предпросмотр поста',

    // Scheduled Posts
    'scheduled_posts.title': 'Запланированные публикации',
    'scheduled_posts.date': 'Дата',
    'scheduled_posts.channel': 'Канал',
    'scheduled_posts.content': 'Контент',
    'scheduled_posts.type': 'Тип',
    'scheduled_posts.actions': 'Действия',
    'scheduled_posts.edit': 'Редактировать',
    'scheduled_posts.delete': 'Удалить',
    'scheduled_posts.no_posts': 'Запланированных публикаций не найдено',
    'scheduled_posts.loading': 'Загрузка запланированных публикаций...',
    'scheduled_posts.confirm_delete': 'Вы уверены, что хотите удалить эту запланированную публикацию?',
    'scheduled_posts.delete_success': 'Публикация удалена из расписания',
    'scheduled_posts.error_delete': 'Не удалось удалить запланированную публикацию',
    'scheduled_posts.error_fetch': 'Не удалось загрузить запланированные публикации',
    'scheduled_posts.error_fetch_single': 'Не удалось загрузить запланированную публикацию',
    'scheduled_posts.scheduled_for': 'Запланировано на',
    'scheduled_posts.back': 'Назад',
    'scheduled_posts.back_to_list': 'Вернуться к списку публикаций',
    'scheduled_posts.confirm_publish_now': 'Вы уверены, что хотите опубликовать этот пост сейчас?',
    'scheduled_posts.publish_now': 'Опубликовать сейчас',
    'scheduled_posts.publish_success': 'Пост опубликован успешно',
    'scheduled_posts.error_publish': 'Не удалось опубликовать пост',
    'scheduled_posts.edit_title': 'Редактирование запланированной публикации',
    'scheduled_posts.delete_confirm_title': 'Удалить запланированную публикацию',
    'scheduled_posts.text_only': 'Только текст',
    'scheduled_posts.image': 'Изображение',
    'scheduled_posts.album': 'Альбом',
    'scheduled_posts.poll': 'Опрос',
    'scheduled_posts.poll_edit_not_available': 'Редактирование опросов пока недоступно',
    'publish_panel.update_success': 'Публикация успешно обновлена',
    'publish_panel.error_updating': 'Не удалось обновить публикацию',

    // Tokens translations for Russian
    'tokens.title': 'Купить AI Токены',
    'tokens.description': 'Увеличьте возможности искусственного интеллекта с помощью дополнительных токенов. Эти токены можно использовать для генерации контента, создания изображений и других AI-функций.',
    'tokens.small_package': '100 AI Токенов',
    'tokens.small_description': 'Идеально для нечастого использования',
    'tokens.large_package': '400 AI Токенов',
    'tokens.large_description': 'Лучшая ценность для регулярных пользователей',
    'tokens.includes': 'Включает {count} AI токенов',
    'tokens.buy_button': 'Купить токены',
    'tokens.note': 'Примечание: Купленные токены будут добавлены на ваш счет сразу после оплаты и не имеют срока действия.',
    'tokens.purchase_success': 'Токены успешно куплены!',
    'tokens.error_purchase': 'Ошибка при обработке покупки токенов',

    // Crypto payment translations
    'crypto.title': 'Оплата криптовалютой',
    'crypto.available': 'Доступна оплата криптовалютой',
    'crypto.description': 'Для оплаты Bitcoin, Ethereum или другими криптовалютами, пожалуйста, свяжитесь с нами через наш Telegram канал.',
    'crypto.contact_button': 'Связаться в Telegram',
    'crypto.benefits': 'Преимущества оплаты криптовалютой: низкие комиссии, быстрые международные транзакции и повышенная конфиденциальность.',

    // Scheduled Posts - Calendar View
    'scheduled_posts.calendar_view': 'Календарь',
    'scheduled_posts.list_view': 'Список',
    'scheduled_posts.post_details': 'Детали публикации',
    'scheduled_posts.poll_details': 'Детали опроса',
    'scheduled_posts.question': 'Вопрос',
    'scheduled_posts.options': 'Варианты ответов',
    
    // Calendar translations
    'calendar.today': 'Сегодня',
    'calendar.previous': 'Назад',
    'calendar.next': 'Вперед',
    'calendar.month': 'Месяц',
    'calendar.week': 'Неделя',
    'calendar.day': 'День',
    'calendar.agenda': 'Повестка',
    'calendar.date': 'Дата',
    'calendar.time': 'Время',
    'calendar.event': 'Событие',
    'calendar.no_events': 'Нет событий в выбранном диапазоне',

    // Drafts translations in Russian
    'dashboard.tab_content_drafts': 'Черновики',
    'drafts.title': 'Мои черновики',
    'drafts.subtitle': 'Сохраняйте и организуйте черновики, шаблоны и идеи для контента',
    'drafts.no_drafts': 'Черновиков не найдено',
    'drafts.create_new': 'Создать новый черновик',
    'drafts.search': 'Поиск черновиков...',
    'drafts.filter_all': 'Все',
    'drafts.filter_with_images': 'С изображениями',
    'drafts.filter_text_only': 'Только текст',
    'drafts.sort_newest': 'Новые',
    'drafts.sort_oldest': 'Старые',
    'drafts.sort_alphabetical': 'По алфавиту',
    'drafts.edit': 'Редактировать',
    'drafts.delete': 'Удалить',
    'drafts.copy_to_post': 'Копировать в пост',
    'drafts.copy_to_poll': 'Копировать в опрос',
    'drafts.created_on': 'Создан: {date}',
    'drafts.updated_on': 'Обновлен: {date}',
    'drafts.confirm_delete': 'Вы уверены, что хотите удалить этот черновик?',
    'drafts.confirm_delete_description': 'Это действие нельзя отменить.',
    'drafts.delete_success': 'Черновик удален',
    'drafts.create_success': 'Черновик создан',
    'drafts.update_success': 'Черновик обновлен',
    'drafts.error_create': 'Не удалось создать черновик',
    'drafts.error_update': 'Не удалось обновить черновик',
    'drafts.error_delete': 'Не удалось удалить черновик',
    'drafts.error_loading': 'Не удалось загрузить черновики',
    'drafts.copied_to_editor': 'Черновик скопирован в редактор',
    'drafts.editor_title': 'Редактор черновиков',
    'drafts.editor_title_placeholder': 'Название черновика',
    'drafts.editor_content_placeholder': 'Напишите свой контент здесь...',
    'drafts.save': 'Сохранить черновик',
    'drafts.cancel': 'Отмена',
    'drafts.title_required': 'Необходимо указать название',
    'drafts.content_required': 'Необходимо добавить содержание',
    'drafts.upload_image': 'Загрузить изображение',
    'drafts.add_tags': 'Добавить теги',
    'drafts.preview': 'Предпросмотр',
    'drafts.editor': 'Редактор',

    // Image position translations
    'publish_panel.image_position': 'Позиция изображения',
    'publish_panel.image_position_top': 'Сверху',
    'publish_panel.image_position_bottom': 'Снизу',
    'publish_panel.image_position_top_description': 'Изображение будет показано вверху поста',
    'publish_panel.image_position_bottom_description': 'Изображение будет показано внизу поста',
    'publish_panel.image_position_help': 'Позиция определяет, где изображение появится в посте',
    'publish_panel.bottom_position_single_image': 'Позиция снизу поддерживает только одно изображение',
    'publish_panel.multiple_images_note': '[Несколько изображений]',
    
    // Inline buttons translations
    'publish_panel.inline_buttons': 'Встроенные кнопки',
    'publish_panel.add_button': 'Добавить кнопку',
    'publish_panel.button_text': 'Текст кнопки',
    'publish_panel.button_url': 'URL кнопки',
    'publish_panel.button_text_placeholder': 'Нажмите здесь',
    'publish_panel.button_url_placeholder': 'https://example.com',
    'publish_panel.remove_button': 'Удалить',
    'publish_panel.max_buttons': 'Максимум 5 кнопок',
    'publish_panel.button_text_required': 'Текст кнопки обязателен',
    'publish_panel.button_url_required': 'URL кнопки обязателен',
    'publish_panel.button_url_invalid': 'Пожалуйста, введите корректный URL',
    'publish_panel.buttons': 'Кнопки Telegram',
    'publish_panel.buttons_note': 'Кнопки будут отображаться одна под другой внизу вашего поста в Telegram.',
    'publish_panel.invalid_url': 'Пожалуйста, введите корректный URL (например, https://example.com)',
    'publish_panel.buttons_not_available_top': 'Кнопки недоступны, когда позиция изображения установлена сверху. Измените позицию изображения на нижнюю, чтобы использовать кнопки.',
    'publish_panel.buttons_cleared': 'Кнопки удалены',
    'publish_panel.buttons_cleared_description': 'Кнопки были удалены, так как они несовместимы с верхним положением изображения.',
  },
};

// Provider component
interface LanguageProviderProps {
  children: ReactNode;
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  // Try to get language from localStorage, default to English
  const [language, setLanguageState] = useState<Language>(() => {
    const savedLanguage = localStorage.getItem('language') as Language;
    return savedLanguage && ['en', 'ru'].includes(savedLanguage) ? savedLanguage : 'en';
  });

  // Update localStorage when language changes
  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  // Set language function
  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  // Translation function
  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

// Custom hook for using the language context
export const useLanguage = () => useContext(LanguageContext); 